/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author MDena
 * https://github.com/WrongCode-01?tab=repositories
 */
public class KirimanPaket extends javax.swing.JFrame {
        String Tanggal, Penerima, JK, Tipe, Jenis, Kurir="";
        int PilihTipe, PilihJenis;
    public KirimanPaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DateChooser21552011440 = new datechooser.beans.DateChooserCombo();
        LabelJudul21552011440 = new javax.swing.JLabel();
        LabelPenerima21552011440 = new javax.swing.JLabel();
        LabelTanggal21552011440 = new javax.swing.JLabel();
        TextFieldPenerima21552011440 = new javax.swing.JTextField();
        LabelJK21552011440 = new javax.swing.JLabel();
        JKL21552011440 = new javax.swing.JRadioButton();
        JKLP21552011440 = new javax.swing.JRadioButton();
        LabelTipePaket21552011440 = new javax.swing.JLabel();
        ComboBoxTP21552011440 = new javax.swing.JComboBox<>();
        LabelJenisPaket21552011440 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListJenisPaket21552011440 = new javax.swing.JList<>();
        LabelKurir21552011440 = new javax.swing.JLabel();
        CheckJNE21552011440 = new javax.swing.JCheckBox();
        CheckSiCepat21552011440 = new javax.swing.JCheckBox();
        CheckGG21552011440 = new javax.swing.JCheckBox();
        CheckJnT21552011440 = new javax.swing.JCheckBox();
        ButtonProses21552011440 = new javax.swing.JButton();
        ButtonBersihkan21552011440 = new javax.swing.JButton();
        ButtonKeluar21552011440 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TampilkanTextArea21552011440 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        DateChooser21552011440.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    DateChooser21552011440.setCalendarBackground(new java.awt.Color(0, 204, 204));

    LabelJudul21552011440.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
    LabelJudul21552011440.setForeground(new java.awt.Color(255, 0, 0));
    LabelJudul21552011440.setText("LAPORAN KIRIMAN PAKET ");

    LabelPenerima21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelPenerima21552011440.setText("ADMIN PENERIMA");

    LabelTanggal21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelTanggal21552011440.setText("TANGGAL BARANG MASUK");

    LabelJK21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelJK21552011440.setText("JENIS KELAMIN");

    JKL21552011440.setBackground(new java.awt.Color(0, 204, 204));
    buttonGroup1.add(JKL21552011440);
    JKL21552011440.setText("LAKI-LAKI");

    JKLP21552011440.setBackground(new java.awt.Color(0, 204, 204));
    buttonGroup1.add(JKLP21552011440);
    JKLP21552011440.setText("PEREMPUAN");

    LabelTipePaket21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelTipePaket21552011440.setText("TIPE PAKET ");

    ComboBoxTP21552011440.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Telah Dibayar", "Cash On Delivery(COD)" }));

    LabelJenisPaket21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelJenisPaket21552011440.setText("JENIS PAKET ");

    ListJenisPaket21552011440.setBackground(new java.awt.Color(0, 204, 204));
    ListJenisPaket21552011440.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "REGULAR", "CEPAT", "SUPER", "SAMEDAY", "INSTANT" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(ListJenisPaket21552011440);

    LabelKurir21552011440.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
    LabelKurir21552011440.setText("KURIR");

    CheckJNE21552011440.setBackground(new java.awt.Color(0, 204, 204));
    CheckJNE21552011440.setText("JNE");
    CheckJNE21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CheckJNE21552011440MouseClicked(evt);
        }
    });

    CheckSiCepat21552011440.setBackground(new java.awt.Color(0, 204, 204));
    CheckSiCepat21552011440.setText("SiCepat");
    CheckSiCepat21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CheckSiCepat21552011440MouseClicked(evt);
        }
    });

    CheckGG21552011440.setBackground(new java.awt.Color(0, 204, 204));
    CheckGG21552011440.setText("GRAB/GOJEK");
    CheckGG21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CheckGG21552011440MouseClicked(evt);
        }
    });

    CheckJnT21552011440.setBackground(new java.awt.Color(0, 204, 204));
    CheckJnT21552011440.setText("J&T");
    CheckJnT21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CheckJnT21552011440MouseClicked(evt);
        }
    });

    ButtonProses21552011440.setBackground(new java.awt.Color(0, 0, 0));
    ButtonProses21552011440.setForeground(new java.awt.Color(255, 255, 255));
    ButtonProses21552011440.setText("PROSES");
    ButtonProses21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonProses21552011440ActionPerformed(evt);
        }
    });

    ButtonBersihkan21552011440.setBackground(new java.awt.Color(0, 0, 0));
    ButtonBersihkan21552011440.setForeground(new java.awt.Color(255, 255, 255));
    ButtonBersihkan21552011440.setText("BERSIHKAN");
    ButtonBersihkan21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonBersihkan21552011440ActionPerformed(evt);
        }
    });

    ButtonKeluar21552011440.setBackground(new java.awt.Color(0, 0, 0));
    ButtonKeluar21552011440.setForeground(new java.awt.Color(255, 255, 255));
    ButtonKeluar21552011440.setText("KELUAR");
    ButtonKeluar21552011440.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButtonKeluar21552011440ActionPerformed(evt);
        }
    });

    TampilkanTextArea21552011440.setEditable(false);
    TampilkanTextArea21552011440.setBackground(new java.awt.Color(0, 204, 204));
    TampilkanTextArea21552011440.setColumns(20);
    TampilkanTextArea21552011440.setRows(5);
    jScrollPane2.setViewportView(TampilkanTextArea21552011440);

    jToolBar1.setRollover(true);

    jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDR\\Pictures\\ScreenShoot\\2022-01-08 11_59_43.png")); // NOI18N
    jButton1.setText("eqwqwd");
    jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    jButton1.setFocusable(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jToolBar1.add(jButton1);

    jToolBar2.setRollover(true);

    jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDR\\Pictures\\ScreenShoot\\2022-01-08 11_59_43.png")); // NOI18N
    jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jToolBar2.add(jButton2);

    jToolBar3.setRollover(true);

    jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDR\\Pictures\\ScreenShoot\\2022-01-08 11_59_43.png")); // NOI18N
    jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    jButton3.setFocusable(false);
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jToolBar3.add(jButton3);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelJudul21552011440)
                    .addGap(97, 97, 97))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelTanggal21552011440)
                        .addComponent(LabelPenerima21552011440)
                        .addComponent(LabelJK21552011440)
                        .addComponent(LabelTipePaket21552011440)
                        .addComponent(LabelJenisPaket21552011440)
                        .addComponent(LabelKurir21552011440))
                    .addGap(32, 32, 32)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JKL21552011440)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JKLP21552011440))
                            .addComponent(DateChooser21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldPenerima21552011440)
                            .addComponent(ComboBoxTP21552011440, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CheckGG21552011440)
                                .addComponent(CheckJNE21552011440))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CheckSiCepat21552011440)
                                .addComponent(CheckJnT21552011440)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ButtonProses21552011440)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ButtonBersihkan21552011440)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ButtonKeluar21552011440)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LabelJudul21552011440)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DateChooser21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTanggal21552011440))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelPenerima21552011440)
                        .addComponent(TextFieldPenerima21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelJK21552011440)
                        .addComponent(JKL21552011440)
                        .addComponent(JKLP21552011440))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelTipePaket21552011440)
                        .addComponent(ComboBoxTP21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelJenisPaket21552011440)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckJNE21552011440)
                        .addComponent(LabelKurir21552011440)
                        .addComponent(CheckSiCepat21552011440))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckGG21552011440)
                        .addComponent(CheckJnT21552011440))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonProses21552011440)
                        .addComponent(ButtonBersihkan21552011440)
                        .addComponent(ButtonKeluar21552011440)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jMenu1.setText("Menu");

    jMenuItem1.setText("Bersihkan");
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("jMenuItem2");
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonProses21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProses21552011440ActionPerformed
        Tanggal=DateChooser21552011440.getText();
        Penerima = TextFieldPenerima21552011440.getText();
        
        PilihTipe=ComboBoxTP21552011440.getSelectedIndex();
        switch(PilihTipe)
        {
            case 0:
                Tipe = "-";
                break;
            case 1:
                Tipe = "TELAH DIBAYAR"; 
                break;
            case 2:
                Tipe= "CASH ON DELIVERY (COD)";
                break;
        }
        PilihJenis=ListJenisPaket21552011440.getSelectedIndex();
        switch(PilihJenis)
        {
            case 0:
                Jenis = "REGULAR";
                break;
            case 1:
                Jenis = "CEPAT";
                break;
            case 2:
                Jenis = "SUPER";
                break;
            case 3:
                Jenis = "SAMEDAY";
                break;
            case 4:
                Jenis = "INSTANT";
                break; 
        }
        if(JKL21552011440.isSelected()){
            JK="LAKI-LAKI";
        }else if(JKLP21552011440.isSelected()){
            JK="PEREMPUAN";
        } else
            JK="-";
                
        TampilkanTextArea21552011440.setText("TANGGAL BARANG MASUK\t    :"+Tanggal+"\nADMIN PENERIMA\t    :"+Penerima+"\nJENIS KELAMIN\t    :"+JK+"\nTIPE PAKET\t\t    :"+Tipe+"\nJENIS PAKET\t\t    :"+Jenis+"\nKURIR\t\t    :"+Kurir);
    }//GEN-LAST:event_ButtonProses21552011440ActionPerformed

    private void ButtonKeluar21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluar21552011440ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonKeluar21552011440ActionPerformed

    private void ButtonBersihkan21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersihkan21552011440ActionPerformed
        TextFieldPenerima21552011440.setText("");
        TampilkanTextArea21552011440.setText("");
        CheckGG21552011440.setSelected(false);
        CheckJNE21552011440.setSelected(false);
        CheckJnT21552011440.setSelected(false);
        CheckSiCepat21552011440.setSelected(false);
    }//GEN-LAST:event_ButtonBersihkan21552011440ActionPerformed

    private void CheckJNE21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckJNE21552011440MouseClicked
         if(CheckJNE21552011440.isSelected()){
            Kurir= Kurir + CheckJNE21552011440.getText()+", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckJNE21552011440MouseClicked

    private void CheckSiCepat21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckSiCepat21552011440MouseClicked
         if(CheckSiCepat21552011440.isSelected()){
            Kurir= Kurir + CheckSiCepat21552011440.getText()+", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckSiCepat21552011440MouseClicked

    private void CheckGG21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckGG21552011440MouseClicked
         if(CheckGG21552011440.isSelected()){
            Kurir= Kurir + CheckGG21552011440.getText() +", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckGG21552011440MouseClicked

    private void CheckJnT21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckJnT21552011440MouseClicked
         if(CheckJnT21552011440.isSelected()){
            Kurir= Kurir + CheckJnT21552011440.getText() + ", ";
        }else{
            Kurir="";
        }
    }//GEN-LAST:event_CheckJnT21552011440MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tanggal=DateChooser21552011440.getText();
        Penerima = TextFieldPenerima21552011440.getText();
        
        PilihTipe=ComboBoxTP21552011440.getSelectedIndex();
        switch(PilihTipe)
        {
            case 0:
                Tipe = "-";
                break;
            case 1:
                Tipe = "TELAH DIBAYAR"; 
                break;
            case 2:
                Tipe= "CASH ON DELIVERY (COD)";
                break;
        }
        PilihJenis=ListJenisPaket21552011440.getSelectedIndex();
        switch(PilihJenis)
        {
            case 0:
                Jenis = "REGULAR";
                break;
            case 1:
                Jenis = "CEPAT";
                break;
            case 2:
                Jenis = "SUPER";
                break;
            case 3:
                Jenis = "SAMEDAY";
                break;
            case 4:
                Jenis = "INSTANT";
                break; 
        }
        if(JKL21552011440.isSelected()){
            JK="LAKI-LAKI";
        }else if(JKLP21552011440.isSelected()){
            JK="PEREMPUAN";
        } else
            JK="-";
                
        TampilkanTextArea21552011440.setText("TANGGAL BARANG MASUK\t    :"+Tanggal+"\nADMIN PENERIMA\t    :"+Penerima+"\nJENIS KELAMIN\t    :"+JK+"\nTIPE PAKET\t\t    :"+Tipe+"\nJENIS PAKET\t\t    :"+Jenis+"\nKURIR\t\t    :"+Kurir);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KirimanPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KirimanPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBersihkan21552011440;
    private javax.swing.JButton ButtonKeluar21552011440;
    private javax.swing.JButton ButtonProses21552011440;
    private javax.swing.JCheckBox CheckGG21552011440;
    private javax.swing.JCheckBox CheckJNE21552011440;
    private javax.swing.JCheckBox CheckJnT21552011440;
    private javax.swing.JCheckBox CheckSiCepat21552011440;
    private javax.swing.JComboBox<String> ComboBoxTP21552011440;
    private datechooser.beans.DateChooserCombo DateChooser21552011440;
    private javax.swing.JRadioButton JKL21552011440;
    private javax.swing.JRadioButton JKLP21552011440;
    private javax.swing.JLabel LabelJK21552011440;
    private javax.swing.JLabel LabelJenisPaket21552011440;
    private javax.swing.JLabel LabelJudul21552011440;
    private javax.swing.JLabel LabelKurir21552011440;
    private javax.swing.JLabel LabelPenerima21552011440;
    private javax.swing.JLabel LabelTanggal21552011440;
    private javax.swing.JLabel LabelTipePaket21552011440;
    private javax.swing.JList<String> ListJenisPaket21552011440;
    private javax.swing.JTextArea TampilkanTextArea21552011440;
    private javax.swing.JTextField TextFieldPenerima21552011440;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
