
package GUI;

public class Latihan1 extends javax.swing.JFrame {
    String nama, pekerjaan;
    
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelJudul21552011440 = new javax.swing.JLabel();
        LabelNama21552011440 = new javax.swing.JLabel();
        LabelPekerjaan21552011440 = new javax.swing.JLabel();
        NamaTextField21552011440 = new javax.swing.JTextField();
        ComboBoxPekerjaan21552011440 = new javax.swing.JComboBox<>();
        ButtonTampil21552011440 = new javax.swing.JButton();
        ButtonClear21552011440 = new javax.swing.JButton();
        ButtonExit21552011440 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TampilTextArea21552011440 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        LabelJudul21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelJudul21552011440.setText("jComboBox Menggunakan method getSelectedItem()");

        LabelNama21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNama21552011440.setText("NAMA");

        LabelPekerjaan21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelPekerjaan21552011440.setText("PEKERJAAN");

        ComboBoxPekerjaan21552011440.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Dosen", "Programmer", "Analis" }));

        ButtonTampil21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonTampil21552011440.setText("TAMPIL");
        ButtonTampil21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTampil21552011440ActionPerformed(evt);
            }
        });

        ButtonClear21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonClear21552011440.setText("CLEAR");
        ButtonClear21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClear21552011440ActionPerformed(evt);
            }
        });

        ButtonExit21552011440.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonExit21552011440.setText("EXIT");
        ButtonExit21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExit21552011440ActionPerformed(evt);
            }
        });

        TampilTextArea21552011440.setColumns(20);
        TampilTextArea21552011440.setRows(5);
        jScrollPane1.setViewportView(TampilTextArea21552011440);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJudul21552011440)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNama21552011440)
                                    .addComponent(LabelPekerjaan21552011440))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaTextField21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxPekerjaan21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonTampil21552011440)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonClear21552011440)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonExit21552011440)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul21552011440)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama21552011440)
                    .addComponent(NamaTextField21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPekerjaan21552011440)
                    .addComponent(ComboBoxPekerjaan21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTampil21552011440)
                    .addComponent(ButtonClear21552011440)
                    .addComponent(ButtonExit21552011440))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonClear21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClear21552011440ActionPerformed
        NamaTextField21552011440.setText("");
        TampilTextArea21552011440.setText("");
    }//GEN-LAST:event_ButtonClear21552011440ActionPerformed

    private void ButtonExit21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExit21552011440ActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonExit21552011440ActionPerformed

    private void ButtonTampil21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTampil21552011440ActionPerformed
        nama = NamaTextField21552011440.getText();
        
        if(ComboBoxPekerjaan21552011440.getSelectedItem()=="Mahasiswa")
            {pekerjaan = "Mahasiswa";}
        else if(ComboBoxPekerjaan21552011440.getSelectedItem()=="Dosen")
            {pekerjaan = "Dosen";}
        else if(ComboBoxPekerjaan21552011440.getSelectedItem()=="Programmer")
            {pekerjaan = "Programmer";}
        else 
        {pekerjaan ="System Analis";}
        
        TampilTextArea21552011440.setText("Nama :\t"+nama+"\nPekerjaan:\t"+pekerjaan);
    }//GEN-LAST:event_ButtonTampil21552011440ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClear21552011440;
    private javax.swing.JButton ButtonExit21552011440;
    private javax.swing.JButton ButtonTampil21552011440;
    private javax.swing.JComboBox<String> ComboBoxPekerjaan21552011440;
    private javax.swing.JLabel LabelJudul21552011440;
    private javax.swing.JLabel LabelNama21552011440;
    private javax.swing.JLabel LabelPekerjaan21552011440;
    private javax.swing.JTextField NamaTextField21552011440;
    private javax.swing.JTextArea TampilTextArea21552011440;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
